# Exercise 3: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [3]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10, 10)
print(A)

[[6.53470851e-01 9.12972480e-01 3.66695937e-01 2.50726523e-01
  1.79728600e-01 9.14111205e-01 4.16726360e-01 6.75506219e-02
  9.66339233e-01 7.13083393e-01]
 [4.19098541e-01 8.18971832e-02 7.07925798e-01 4.38092588e-01
  8.31288670e-01 3.96046118e-01 1.46785882e-01 5.28332865e-01
  6.55320705e-01 8.96175522e-01]
 [1.08149646e-01 2.28919659e-02 1.97940254e-01 7.81837320e-01
  6.86993419e-01 2.91541110e-01 5.14836263e-01 5.33396933e-02
  2.20760056e-01 3.06117881e-01]
 [6.69598660e-01 1.86591148e-01 8.84659551e-01 7.32942478e-02
  3.89627172e-01 8.88678608e-01 3.00441533e-01 3.06981450e-01
  4.93649735e-02 6.30072287e-01]
 [9.85488080e-02 7.54030682e-01 7.46013804e-02 1.23144330e-01
  2.63873023e-01 7.00882097e-01 8.20463227e-01 7.38789537e-01
  4.32486662e-01 9.53040344e-01]
 [9.80555888e-01 2.06152401e-02 7.70601098e-01 8.61894849e-01
  2.22217206e-01 8.32685193e-01 9.59846414e-01 3.12032369e-01
  9.55316363e-01 8.53230246e-01]
 [7.54325864e-01 9.45836305e-01 5.87163904e-01 6.78240099e

In [9]:
#3.3: return only the odd rows of A
A[::2,:]

array([[6.53470851e-01, 9.12972480e-01, 3.66695937e-01, 2.50726523e-01,
        1.79728600e-01, 9.14111205e-01, 4.16726360e-01, 6.75506219e-02,
        9.66339233e-01, 7.13083393e-01],
       [1.08149646e-01, 2.28919659e-02, 1.97940254e-01, 7.81837320e-01,
        6.86993419e-01, 2.91541110e-01, 5.14836263e-01, 5.33396933e-02,
        2.20760056e-01, 3.06117881e-01],
       [9.85488080e-02, 7.54030682e-01, 7.46013804e-02, 1.23144330e-01,
        2.63873023e-01, 7.00882097e-01, 8.20463227e-01, 7.38789537e-01,
        4.32486662e-01, 9.53040344e-01],
       [7.54325864e-01, 9.45836305e-01, 5.87163904e-01, 6.78240099e-01,
        3.04402725e-01, 3.86907850e-02, 8.95966283e-01, 6.11047030e-01,
        6.91149536e-01, 5.29131999e-01],
       [9.00706755e-01, 7.11758899e-04, 1.38077194e-01, 6.94610859e-01,
        9.55815340e-01, 8.18566380e-01, 4.89527815e-01, 9.04799479e-01,
        5.14621873e-01, 4.57210917e-01]])

In [11]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[3.94629765, 2.59867879, 1.39992263, 2.47600797, 2.98848973,
        3.91202296, 3.29174296, 3.1735583 , 2.82252092, 2.19999144],
       [2.59867879, 3.25658567, 1.73915366, 2.43343668, 2.3550199 ,
        3.54669591, 2.75623968, 2.82592233, 3.19521863, 2.76573493],
       [1.39992263, 1.73915366, 1.62997116, 1.21068656, 1.37360919,
        2.31122914, 1.77855552, 1.64264998, 2.11697252, 1.87006807],
       [2.47600797, 2.43343668, 1.21068656, 2.7966629 , 2.10250714,
        3.20081024, 2.22799434, 2.4759148 , 2.61447256, 2.437364  ],
       [2.98848973, 2.3550199 , 1.37360919, 2.10250714, 3.47416921,
        3.16242315, 3.01203315, 2.94532214, 2.73947431, 2.36393701],
       [3.91202296, 3.54669591, 2.31122914, 3.20081024, 3.16242315,
        5.70064929, 4.05845324, 3.54923748, 4.11622979, 3.22215276],
       [3.29174296, 2.75623968, 1.77855552, 2.22799434, 3.01203315,
        4.05845324, 4.29634531, 2.90078699, 3.14399131, 2.58222307],
       [3.1735583 , 2.82592233, 1.6426499

In [16]:
#3.5: compute the matrix inverse of A
A_inv = np.linalg.inv(A)
np.isclose(A.dot(A_inv), np.identity(10))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [18]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
indices = np.where((A>0.5))
A[indices] = A[indices]/2
A

array([[0.32673543, 0.45648624, 0.36669594, 0.25072652, 0.1797286 ,
        0.4570556 , 0.41672636, 0.06755062, 0.48316962, 0.3565417 ],
       [0.41909854, 0.08189718, 0.3539629 , 0.43809259, 0.41564433,
        0.39604612, 0.14678588, 0.26416643, 0.32766035, 0.44808776],
       [0.10814965, 0.02289197, 0.19794025, 0.39091866, 0.34349671,
        0.29154111, 0.25741813, 0.05333969, 0.22076006, 0.30611788],
       [0.33479933, 0.18659115, 0.44232978, 0.07329425, 0.38962717,
        0.4443393 , 0.30044153, 0.30698145, 0.04936497, 0.31503614],
       [0.09854881, 0.37701534, 0.07460138, 0.12314433, 0.26387302,
        0.35044105, 0.41023161, 0.36939477, 0.43248666, 0.47652017],
       [0.49027794, 0.02061524, 0.38530055, 0.43094742, 0.22221721,
        0.4163426 , 0.47992321, 0.31203237, 0.47765818, 0.42661512],
       [0.37716293, 0.47291815, 0.29358195, 0.33912005, 0.30440273,
        0.03869078, 0.44798314, 0.30552351, 0.34557477, 0.264566  ],
       [0.3857366 , 0.25170088, 0.3962696